### PR TITLE
First aid integration

### PR DESCRIPTION
**Pull request by ichttt**
This is a initial implementation of FirstAid compatibility in SD.
It only covers a damage distribution thrist, as shivaxi and I concluded that the default random distribution is appropiate for the other damage sources.
Tested and confirmed to be working

### CODE REVIEW

**Comment by Charles445** [comment]
Would the 'load after' dependency be necessary if the compat initialization ran on postInit instead?
I think First Aid finalizes the registry on loadComplete so I don't think there'd be any race condition issues

**Comment by ichttt** [comment]
The load order dependency isn't strictly needed, but I included it for a version check, so you don't run into issues with too old firstaid versions

**Comment by Charles445** [comment]
Mind if I fiddle with this after I pull it?
I plan on refactoring this over to the compat mod folder, turn it into a soft dependency like the others, move it to postInit, remove the version check, and add a firstaid hardmode check

**Comment by ichttt** [comment]
go ahead, do as you like. It's you mod after all :P

**Pull request merged**
